[package]
name = "lioqing"
version = "0.1.0"
authors = ["Lio Qing"]
edition = "2021"

[[bin]]
name = "background"
path = "src/bin/native_background.rs"

[[bin]]
name = "copy-image-assets"
path = "src/bin/copy_image_assets.rs"

[dependencies]
bytemuck = "1.21"
chrono = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
itertools = "0.14"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
wgpu = { version = "25.0", features = ["webgl"] }
winit = "0.30"

[target.'cfg(target_arch = "wasm32")'.dependencies]
bitflags = { version = "2.9", features = ["serde"] }
codee = { version = "0.3", features = ["json_serde_wasm", "json_serde"] }
console_error_panic_hook = "0.1"
console_log = { version = "1.0", features = ["color"] }
fuzzy-matcher = "0.3.7"
leptos = { version = "0.7", features = ["csr"] }
leptos-use = "0.15"
leptos_router = "0.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"
futures = "0.3"
walkdir = "2.5"
